export enum ROUTE_NAME {
    // Auth
    AUTH = 'AUTH.AUTH',
    // Guest
    GUEST_HOME = 'GUEST.HOME',
    // Main
    MAIN = 'MAIN',
    MAIN_GENERATE = 'MAIN.GENERATE',
    MAIN_MYQR = 'MAIN.MYQR',
    MAIN_PROFILE = 'MAIN.PROFILE',
    MAIN_PAYMENT = 'MAIN.PAYMENT',
    MAIN_REFERAL = 'MAIN.REFERALS',

    QR_GENERATE = 'QR.GENERATE',
    // Public
    PUBLIC_QR = 'PUBLIC.QR',
    PUBLIC_PAYMENT = 'PUBLIC.PAYMENT',
}
